use_frameworks!

def temp_override
    pod 'KeyedCodable', :git => "https://github.com/ajpallares/KeyedCodable.git" , :commit => "2c823cf86cb8d162f5ca53cb484b10152f4142bb"
end
target 'SDOSAlamofire_Example' do
    temp_override
  pod 'SDOSAlamofire', :path => '../'
  pod 'OHHTTPStubs'
end
