source 'https://github.com/SDOSLabs/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
install! 'cocoapods', :deterministic_uuids => false
use_frameworks!
inhibit_all_warnings!

def shared_pods
    pod 'SDOSAlamofire/JSONAPI', :path => '../../', :inhibit_warnings => false
  	pod 'OHHTTPStubs', '6.1.0'
  	pod 'SDOSKeyedCodable'
end

target 'SDOSAlamofireSample' do
  shared_pods
end
