source 'http://svrgitpub.sdos.es/ios/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
install! 'cocoapods', :deterministic_uuids => false
use_frameworks!
inhibit_all_warnings!

def shared_pods
  	pod 'OHHTTPStubs'
end

target 'SDOSAlamofireSample' do
  shared_pods
end
